config/routes.rb
Rails.application.routes.draw do
  root 'menu#index'
 
  get 'menu' => 'menu#index'

  get 'menu/food' #=> 'menu#beverages' redirect food to beverages action

  get 'menu/beverages'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/menu.rb
class Menu 
  include HTTParty 
  ENV["FOOD2FORK_KEY"] = '83a68d71762d61bc96b9e528297679f0'
			 
  base_uri 'http://food2fork.com/api'
  default_params key: ENV["FOOD2FORK_KEY"]
  format :json
  
  def self.for term
    get("/search", query: {q: term})["recipes"]
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/menu_controller.rb
class MenuController < ApplicationController
  def index
    @time = Time.now
    @search_term = params[:looking_for] || 'meat' #http://10.0.223.4:3000/menu?looking_for=salad
    @menus = Menu.for(@search_term)
  end

  def food
    @food = ['pizza', 'pasta', 'salad']
  end

  def beverages
    @drinks = ['water', 'juice', 'beer']
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/menu_helper.rb
module MenuHelper
  def formatted_time(time)
    time.strftime("%I:%M%p")
  end
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Status</title>
    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'true' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'true' %>
    <%= csrf_meta_tags %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/layouts/status.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Status</title>
    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'true' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'true' %>
    <%= csrf_meta_tags %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/menu/beverages.html.erb
<h1>Menu#beverages</h1>
<p>Please choose from:</p>
<% @drinks.each do |d|%>
  <p><%= d %></p>
<% end %>

app/views/menu/food.html.erb
<h1>Menu#food</h1>
<p>Please choose from:</p>
<% @food.each do |f| %>
  <p><%= f %></p>
<% end %>

app/views/menu/index.html.erb
<h1>Menu</h1>
<p>Welcome to <%= link_to "Menu", menu_path %></p>
<p><%= formatted_time(@time) %></p>
<p>Please choose menu</p>
<p><%= link_to "Food", menu_food_path %></p>
<p><%= link_to "Beverages", menu_beverages_path %></p>

<h1>Searching for <%= @search_term %></h1>
<table border ="1">
  <tr>
    <th>Image</th>
    <th>Publisher</th>
    <th>Recipe Name</th>
  </tr>
  <% @menus.each do |recipe| %>
    <tr class=<%= cycle('even','odd')%>>
      <td><%= image_tag(recipe["image_url"]) %></td>
      <td><%= recipe["publisher"] %></td>
      <td><%= recipe["title"] %></td>
    </tr>
  <% end %>
</table>